export enum SETTINGS {
  PORT = '3000',

  PG_PORT = 'PG_PORT',
  PG_DB_NAME = 'PG_DB_NAME',
  PG_USER_NAME = 'PG_USER_NAME',
  PG_PASS = 'PG_PASS',

  MONGO_URL = 'MONGO_URL',
  DB_NAME = 'DB_NAME',

  BASIC_AUTH = 'BASIC_AUTH',
  JWT_SECRET = 'JWT_SECRET',
  EXPIRESIN_ACCESS_TOKEN = 'EXPIRESIN_ACCESS_TOKEN',
  EXPIRESIN_REFRESH_TOKEN = 'EXPIRESIN_REFRESH_TOKEN',

  TEST_EMAIL = 'TEST_EMAIL',
  TEST_PASS = 'TEST_PASS',

  COOKIE_HTTP_ONLY = 'COOKIE_HTTP_ONLY',
  COOKIE_SECURE = 'COOKIE_SECURE',

  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLR_LIMIT = 'THROTTLR_LIMIT',

  REFRESH_TOKEN_COOKIE_NAME = 'refreshToken',

  POST_MAIN_IMAGES_BUCKET = 'POST_MAIN_IMAGES_BUCKET',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',

  TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_TOKEN',

  SERVEO_URL = 'SERVEO_URL',
}
