export enum SETTINGS {
  PORT = '3000',

  MONGO_URL = 'MONGO_URL',
  DB_NAME = 'DB_NAME',

  BASIC_AUTH = 'BASIC_AUTH',
  JWT_SECRET = 'JWT_SECRET',
  EXPIRESIN_ACCESS_TOKEN = 'EXPIRESIN_ACCESS_TOKEN',
  EXPIRESIN_REFRESH_TOKEN = 'EXPIRESIN_REFRESH_TOKEN',

  TEST_EMAIL = 'TEST_EMAIL',
  TEST_PASS = 'TEST_PASS',

  COOKIE_HTTP_ONLY = 'COOKIE_HTTP_ONLY',
  COOKIE_SECURE = 'COOKIE_SECURE',

  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLR_LIMIT = 'THROTTLR_LIMIT',

  REFRESH_TOKEN_COOKIE_NAME = 'refreshToken',
}
